apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"ingress-nginx","app.kubernetes.io/name":"ingress-nginx"},"name":"ingress-nginx"}}
  creationTimestamp: "2025-06-19T16:33:13Z"
  labels:
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
    kubernetes.io/metadata.name: ingress-nginx
  name: ingress-nginx
  resourceVersion: "491990"
  uid: 10a77429-8f34-4f15-b4ac-f07f837344bb
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
