apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus
    meta.helm.sh/release-namespace: monitoring
  creationTimestamp: "2025-06-25T20:53:04Z"
  labels:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: prometheus-pushgateway
    app.kubernetes.io/version: v1.11.1
    helm.sh/chart: prometheus-pushgateway-3.4.0
  name: prometheus-prometheus-pushgateway
  namespace: monitoring
  resourceVersion: "1677329"
  uid: a5c2a814-80ef-4213-a706-7ba88d6b42d4
