apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus
    meta.helm.sh/release-namespace: monitoring
  creationTimestamp: "2025-06-25T20:53:04Z"
  labels:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/version: v0.28.1
    helm.sh/chart: alertmanager-1.21.0
  name: prometheus-alertmanager
  namespace: monitoring
  resourceVersion: "1677331"
  uid: e4af254f-16c7-4c08-b399-5a3eff8994cc
