apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus
    meta.helm.sh/release-namespace: monitoring
  creationTimestamp: "2025-06-25T20:53:04Z"
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: prometheus-node-exporter
    app.kubernetes.io/part-of: prometheus-node-exporter
    app.kubernetes.io/version: 1.9.1
    helm.sh/chart: prometheus-node-exporter-4.47.0
  name: prometheus-prometheus-node-exporter
  namespace: monitoring
  resourceVersion: "1677328"
  uid: 1848f274-ea7d-44f0-ae49-40ccad5884b7
