apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus
    meta.helm.sh/release-namespace: monitoring
  creationTimestamp: "2025-06-25T20:53:04Z"
  labels:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/version: v0.28.1
    helm.sh/chart: alertmanager-1.21.0
  name: prometheus-alertmanager-headless
  namespace: monitoring
  resourceVersion: "1677339"
  uid: a0a61aa0-cb09-4f4d-a631-eeaf982fe958
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 9093
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: alertmanager
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
