apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus
    meta.helm.sh/release-namespace: monitoring
    prometheus.io/probe: pushgateway
  creationTimestamp: "2025-06-25T20:53:04Z"
  labels:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: prometheus-pushgateway
    app.kubernetes.io/version: v1.11.1
    helm.sh/chart: prometheus-pushgateway-3.4.0
  name: prometheus-prometheus-pushgateway
  namespace: monitoring
  resourceVersion: "1677350"
  uid: 2ea91b13-d055-480d-893a-69b31dff6cf5
spec:
  clusterIP: 10.97.175.75
  clusterIPs:
  - 10.97.175.75
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 9091
    protocol: TCP
    targetPort: 9091
  selector:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: prometheus-pushgateway
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
